Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -24,8 +24,8 @@ jobs:
         run: pip install -r requirements.txt
 
       - name: Run tests
-        #run: pytest || echo "No tests yet"
-        run: exit 1   # always fail
+        run: pytest || echo "No tests yet"
+       # run: exit 1   # always fail
 
       # Report Deployment on Success
       - name: Report Deployment to Datadog (DORA Metrics)
